#!/usr/bin/env bash
# Creates a file /var/run/holbertonscript.pid containing the script PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" upon receiving a SIGTERM
# Displays "Y U no love me?!" upon receiving a SIGINT
# Deletes the file /var/run/holbertonscript.pid and terminates upon
# receiving a SIGQUIT or SIGTERM

# Create the pid file
echo "$$" > /var/run/holbertonscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
 	trap 'echo "Y U no love me?!"' SIGINT
 	trap 'echo "I hate the kill command" && rm -f /var/run/myscript.pid; exit ' SIGTERM
	trap "rm -f /var/run/myscript.pid; exit" SIGQUIT

done
