#!/usr/bin/env bash
# Run Nginx as Nginx

# Stop nginx if it's currently running
service nginx stop

# Change nginx user in nginx.conf
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Change ownership of nginx directories to nginx user
chown -R nginx:nginx /var/log/nginx /var/lib/nginx

# Configure nginx to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Start nginx
service nginx start
